// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_hello.proto

/*
Package __test_hello_service is a generated protocol buffer package.

It is generated from these files:
	test_hello.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	GoodbyeRequest
	GoodbyeReply
*/
package test_hello_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GoodbyeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GoodbyeRequest) Reset()                    { *m = GoodbyeRequest{} }
func (m *GoodbyeRequest) String() string            { return proto.CompactTextString(m) }
func (*GoodbyeRequest) ProtoMessage()               {}
func (*GoodbyeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GoodbyeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GoodbyeReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *GoodbyeReply) Reset()                    { *m = GoodbyeReply{} }
func (m *GoodbyeReply) String() string            { return proto.CompactTextString(m) }
func (*GoodbyeReply) ProtoMessage()               {}
func (*GoodbyeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GoodbyeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "test_hello_service.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "test_hello_service.HelloReply")
	proto.RegisterType((*GoodbyeRequest)(nil), "test_hello_service.GoodbyeRequest")
	proto.RegisterType((*GoodbyeReply)(nil), "test_hello_service.GoodbyeReply")
}

func init() { proto.RegisterFile("test_hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x49, 0x2d, 0x2e,
	0x89, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x42, 0x88,
	0xc4, 0x17, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x4a, 0x49, 0xa6, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4,
	0xea, 0x83, 0x55, 0x24, 0x95, 0xa6, 0xe9, 0x27, 0xe6, 0x55, 0x42, 0x94, 0x4b, 0x49, 0xa3, 0x4b,
	0xa5, 0xe6, 0x16, 0x94, 0x40, 0x25, 0x95, 0x94, 0xb8, 0x78, 0x3c, 0x40, 0x06, 0x05, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x6a, 0x5c, 0x5c, 0x50, 0x35, 0x05, 0x39, 0x95, 0x42, 0x12,
	0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0x45, 0x30, 0xae, 0x92, 0x0a, 0x17, 0x9f,
	0x7b, 0x7e, 0x7e, 0x4a, 0x52, 0x65, 0x2a, 0x3e, 0xd3, 0x34, 0xb8, 0x78, 0xe0, 0xaa, 0xf0, 0x9a,
	0x67, 0xb4, 0x9e, 0x91, 0x8b, 0x3b, 0x24, 0xb5, 0xb8, 0x24, 0x18, 0xe2, 0x47, 0x21, 0x1f, 0x2e,
	0x8e, 0xe0, 0xc4, 0x4a, 0xb0, 0x53, 0x84, 0x14, 0xf4, 0x30, 0x03, 0x41, 0x0f, 0xd9, 0x27, 0x52,
	0x72, 0x78, 0x54, 0x80, 0xec, 0x0d, 0xe2, 0xe2, 0x0a, 0x4e, 0xac, 0x84, 0x3a, 0x45, 0x48, 0x09,
	0x9b, 0x6a, 0x54, 0xdf, 0x48, 0x29, 0xe0, 0x55, 0x53, 0x90, 0x53, 0xe9, 0x24, 0x16, 0x25, 0xa2,
	0x67, 0x8d, 0xa9, 0x28, 0x89, 0x0d, 0x1c, 0xd8, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43,
	0xfd, 0xc1, 0x04, 0xcc, 0x01, 0x00, 0x00,
}
